### ISSUE TITLE
Can´t  install without composer

### ISSUE THREAD

**Issue by quadronet** [AgrosupDijon-DSI/bulma-package#10]
The ext. can´t installed without composer and PHP 8.1.

**Comment by wtfred** [comment]
Hi @quadronet , did you try the version 2.0.0 i just released yesterday on TER? (Or version 1.8.1 if you are still on TYPO3 10.4)

With composer: you can install version 2.0.0 on PHP >=7.4
Without composer: install version 2.0.0 from TER or Extension manager

**Comment by wtfred** [comment]
I'm closing this issue due to no feedback for a month. Feel free to comment if you still have problem.
