### ISSUE TITLE
Multilanguage not working

### ISSUE THREAD

**Issue by mamathemes** [AgrosupDijon-DSI/bulma-package#11]
Unfortunately the translations are not working. When I translate a page in another language and try to view it I get the following error:

(1/1) #1476107295 TYPO3\CMS\Core\Error\Exception

PHP Warning: Undefined array key "sys_language_uid" in /var/www/html/typo3/.../typo3_src-11.5.17/typo3/sysext/core/Classes/Domain/Repository/PageRepository.php line 628

**Comment by wtfred** [comment]
Indeed, i will work on that, thanks for reporting.

**Comment by wtfred** [comment]
This is a TYPO3 core issue (see https://forge.typo3.org/issues/98404), and should be fixed in TYPO3 11.5.18
That being said, i will still see if i can make some change on my side to not trigger the warning

**Comment by mamathemes** [comment]
Thank's a lot!

**Comment by wtfred** [comment]
@mamathemes Can you try with new version 2.0.1? (Should be available on TER soon if you don't work with composer)

**Comment by mamathemes** [comment]
Will try, sure.

**Comment by mamathemes** [comment]
Yeah, the error is gone. Translations are working now. I appreciate your very quick fixing of this issue. Chapeau!

May I ask you something else? I coded on typo3 several times since version 4. I did not love it very much but beginning with version 9 I tested a bit more and now I am deciding to give typo3 more priority as before. I use the "scan extension" very often and I recognized that a lot of extensions, including important extensions like bootstrap and news p. e., aren't green colored but red. Do you know why?

Regarding to your Bulma extension there are only 2 important issues shown as you can see in the screen but some others have lot's of issues shown at "scan extensions".

Is this an issue I should be focused at or not?

What do you think?

Thank's again very much!

Wolfgang

![bulma201_extensionscan_27102023](https://user-images.githubusercontent.com/32773052/198254207-fbdd22d7-cf47-450b-9295-baf1f12509e4.png)

**Comment by wtfred** [comment]
Thank you for testing, i will close the issue.

Regarding your question, as written in the description of the "Scan extension" panel, this module is for extension developers & site mainteners, and false positives are impossible to avoid.
For my case, i'm "red", but warning are weak, "probable match, but can be a false positive" (and they are false positives).
I'd say yes it's always usefull to check, but when warnings are "weak", it is probably ok. The more big the extension is, the more false positive can happened.
So, don't ignore, but maybe don't focus on it when warnings are "weak"
