### ISSUE TITLE
column page layout missing

### ISSUE THREAD

**Issue by mikeemike7** [AgrosupDijon-DSI/bulma-package#6]
Hi Sébastien Convers,

thanks for Bulma package for Typo3 - this is so cool! 

Is there a chance to get a column page layout for content, soon? Then it would be nearly perfect even for users with less experience in coding ;-). Thanks a lot.

**Comment by wtfred** [comment]
Hello Mike,

At the moment, we don't want to manage a bunch of page layouts, as it will never fit everyone needs. Maybe later if this become a popular demand, but for now you are the first "official" user of our package (thanks for that btw :heart:)

But what we can do, "soon" , is:
- While waiting for the [structured content initiative](https://typo3.org/community/teams/typo3-development/initiatives/structured-content), we can make an integration of [EXT:container](https://extensions.typo3.org/extension/container), if present on the website, to allow editors to create columns container when they need it. 
- make a documentation on how to implement your own page layout

**Comment by wtfred** [comment]
We added some backend layouts with this MR https://github.com/AgrosupDijon-DSI/bulma-package/pull/7
It's available on 1.8.0 for TYPO3 10 and on master for TYPO3 11 (no stable release yet)
