### ISSUE TITLE
Update scssphp Lib

### ISSUE THREAD

**Issue by weisgerberm** [AgrosupDijon-DSI/bulma-package#9]
The compiler crashes when opening the frontend.
Please update the scssphp version like it is in bootstrap_package (https://github.com/benjaminkott/bootstrap_package/tree/master/Contrib/scssphp)

Error: Method 'setOutputStyle' not found in \ScssPhp\ScssPhp\Compiler 

My project was not setup with composer. I loaded the package from github

Thanks

**Comment by wtfred** [comment]
Hello ,

What version of bulma_package are you using?
If you are on 1.8.0, then i will update scssphp for this version, but if you are on master, be aware that we will most likely drop "non composer" support when we will release a stable version 2.0.0, or in the near future.
It's not 100% decided yet, but chances are high...

**Comment by weisgerberm** [comment]
Hello,

thanks for the response. I'm on 2.0.0/master. 
When you're going to release the version for TER, then the extension should work out of the box even for non-composer support, I think.
Not everyone has access to composer e.g. when you're on a shared server. So it would sadly not be possible to install this extension anymore (without knowledge)

**Comment by wtfred** [comment]
You are right, and i just looked into how EXT:crawler is dealing with composer dependencies, and i will implement the same for TER installation. (https://github.com/tomasnorre/crawler/commit/06175e63d329886dcc19273728f9d8a9d9e4a09c)

It won't fix your problem though, as cloning github project will still require composer to work ^^
But maybe you are using github only because i didn't release v2.0.0 on TER yet?

**Comment by wtfred** [comment]
Hello @weisgerberm,

Can you try the version 2.0.0 from TER and let me know how it goes? (Don't use github version, or you will still have to use composer to install dependencies)

**Comment by weisgerberm** [comment]
Hi @wtfred

iI just updated the extension from TER and it seems to work great. Thank you :)

**Comment by wtfred** [comment]
Perfect then :+1: 

Fixed by 2ef4a2f1
